Network: Add support for parsing multipath routing
chef/ohai pull request #1736
Opened 2022-02-17 22:43 UTC by anitazha

Signed-off-by: Anita Zhang <the.anitazha@gmail.com>

## Description
We have some hosts using multipath routing and the network plugin is failing to set any interface information for the interfaces with such multipath configuration. This PR updates `check_routing_table()` in the network plugin to support multipath routing.

## Related Issue

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2022-02-23 00:10 UTC, jaymzh requested changes

2022-02-23 00:10 UTC, jaymzh commented on lib/ohai/plugins/linux/network.rb
>          route_endings = parts
This is pretty confusing way to do this in ruby.

The hidden shift changes parts, and then you assign a pointer of parts to route_endings (everything in ruby is a pointer).

It totally works, but I'd much rather something like this, which I find easier to follow:

```ruby
# If we have multiroute, then the first part will be a normal looking route:
#   default proto ra metric 1024 <other options>
# and then each successive part after that is hops that won't have those options.
# so the first thing we do, is grab that first part, and split it in to the route dest ("default")
# in the above, and then all the options for that route. 
parts = line.split('\\')
route_dest, dest_opts = parts.first.split(nil, 2)
# then all the route endings, generally just hops:
route_endings = parts[1..]
if dest_parts.count > 1
  # your comment here, it's excellent.
  route_endings.map! { |e| e.include?("nexthop") ? "#{dest_opts} #{e}" : e }
end
```

2022-02-23 00:10 UTC, jaymzh commented on spec/unit/plugins/linux/network_spec.rb
> +          expect(plugin["network"]["interfaces"]["eth0"]["routes"]).to eq([Mash.new( destination: "default", family: "inet6", proto: "ra", "via": "fe80::c018:50ff:fe41:ca33", "metric": "1024" )])
be consistent on your hash syntax
```suggestion
          expect(plugin["network"]["interfaces"]["eth0"]["routes"]).to eq([Mash.new( destination: "default", family: "inet6", proto: "ra", via: "fe80::c018:50ff:fe41:ca33", metric: "1024" )])
```

2022-02-23 00:10 UTC, jaymzh commented on spec/unit/plugins/linux/network_spec.rb
> +          expect(plugin["network"]["interfaces"]["eth3"]["routes"]).to eq([Mash.new( destination: "default", family: "inet6", proto: "ra", "via": "fe80::c018:50ff:fe3f:9184", "metric": "1050" )])
same

2022-02-23 00:10 UTC, jaymzh commented on lib/ohai/plugins/linux/network.rb
> +        dest_parts = parts.shift.strip.split("\s", 2)
don't specify `\s`, just use the default splitting which is smart whitespace split.

2022-02-23 01:27 UTC, anitazha commented
Thanks Phil! Updated with your suggestions

2022-02-23 20:01 UTC, jaymzh reviewed
Code looks good, sorry I missed the lack of v4-test below, but I suspect that's gonna be the most-commonly-used path in the code, so lets just have a test for it as well?

2022-02-23 20:01 UTC, jaymzh commented on spec/unit/plugins/linux/network_spec.rb
> +        let(:linux_ip_route) { "" }
just to make sure people don't break this in the future, can we add a v4 test, please?

2022-02-24 08:07 UTC, anitazha commented
There was an existing test case for multipath IPv4 but without the extra options on the first line (line 165 of network_spec.rb). The IPv4 test case I added includes options.

2022-02-25 19:31 UTC, jaymzh approved these changes

2022-02-25 19:32 UTC, jaymzh commented
Looks great. I'll merge when tests pass. I'm out of town this weekend so feel free to poke me next week if I haven't merged.

2022-02-25 19:39 UTC, merged

2022-02-25 19:53 UTC, tas50 commented
@anitazha is this something we'd want to backport to Ohai 16 and 17?

2022-02-28 09:05 UTC, anitazha commented
@tas50 It could be useful to have since any default IPv6 routes with options using multipath just break without it. But I think multipath routing isn't super widely used so most people won't run into it.