Use a minimum of 1 thread per core for CPU total calculation
chef/ohai pull request #1756
Opened 2022-07-05 17:33 UTC by stanhu

## Description

In some LXD containers running with VT-x hardware virtualization, it
appears that threads per core is 0, resulting in a total number of
CPUs of 0. Add a test case and handle some quirks with the `lscpu`
output.

## Related Issue

Closes https://github.com/chef/ohai/issues/1755

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2022-07-07 23:13 UTC, ramereth commented
LGTM

2022-07-19 19:59 UTC, johnmccrae commented
Please update the description to show why the default cpu is configurable.

2022-07-19 20:39 UTC, stanhu commented
> Please update the description to show why the default cpu is configurable.

@johnmccrae Could you elaborate? I don't quite understand.

2022-08-02 22:35 UTC, stanhu commented
https://github.com/chef/ohai/pull/1761 might be an alternative solution: if we get 0, give up and use `/proc/cpuinfo`.

2022-08-09 19:34 UTC, jaymzh commented
> > Please update the description to show why the default cpu is configurable.
> 
> @johnmccrae Could you elaborate? I don't quite understand.

@stanhu - Your change to do `max[val, 1]` is obviously correct. But you changed all the tests to stop checking for CPU 0 and start looking for some configurable "default_cpu" - but your PR description doesn't mention this change at all or why you are making it.

2022-08-23 19:55 UTC, jaymzh commented
Ping @stanhu ?

2022-08-30 19:41 UTC, jaymzh requested changes
Thanks. Looks good, minus the lint failures. Can you run the rubocop autocorrecting rake task? @tpowell-progress is trying to find the exact command.

2022-08-30 20:08 UTC, stanhu commented
> Thanks. Looks good, minus the lint failures. Can you run the rubocop autocorrecting rake task? @tpowell-progress is trying to find the exact command.

I manually corrected them. Running `diff --name-only main | xargs bundle exec rubocop -a` corrected almost the entire file. 😄

2022-09-06 19:47 UTC, jaymzh approved these changes

2022-09-06 19:48 UTC, marcparadise approved these changes

2022-09-06 19:48 UTC, merged

2022-09-06 19:48 UTC, jaymzh commented
Thanks!