Testing new Linux Network Plugin settings ported from Chef-18
chef/ohai pull request #1778
Opened 2023-01-19 04:40 UTC by johnmccrae

Signed-off-by: John McCrae <john.mccrae@progress.com>

## Description

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2023-01-23 14:38 UTC, PrajaktaPurohit approved these changes

2023-01-24 20:41 UTC, jaymzh commented
Did you `git cherry-pick` this (plus add the `rescue`)? Or did you manually backport this change? If it's manual, I'd want to go through and have a 2nd person compare this very carefully. If you `git cherry-pick`d and it was clean, then I'd say merge away.

2023-01-24 20:45 UTC, tpowell-progress requested changes
@johnmccrae just clarifying that this is a cherry pick and not a manual apply

2023-01-25 08:14 UTC, neha-p6 commented
> Did you `git cherry-pick` this (plus add the `rescue`)? Or did you manually backport this change? If it's manual, I'd want to go through and have a 2nd person compare this very carefully. If you `git cherry-pick`d and it was clean, then I'd say merge away.

It was a manual chance, since @johnmccrae found difference code base between `main` and `16-stable`. We will take a relook before merging to avoid any human error.

2023-01-25 09:30 UTC, merged