Hab plan file for windows and linux to build hab pkg
chef/ohai pull request #1840
Opened 2024-09-17 05:35 UTC by sanghinitin

Hab plan file for windows and linux to build hab pkg

2024-09-20 06:08 UTC, sanjain-progress commented on habitat/plan.sh
> +    gem install chef-utils chef-config
@sanghinitin why we are installing these gem manually. In Gemfile we specify this gem to download from there respective repo and use main branch. `gem install use` from rubygem.org

2024-09-25 08:30 UTC, sanjain-progress commented on .byebug_history
> +next
This file need to be removed

2024-09-25 08:32 UTC, sanjain-progress approved these changes

2024-10-17 07:34 UTC, nikhil2611 approved these changes

2024-10-22 20:56 UTC, sean-simmons-progress requested changes
Is the idea here to also build this using expeditor? If so we need to configure the pipeline to do so.

2024-10-23 07:14 UTC, sanghinitin commented
> Is the idea here to also build this using expeditor? If so we need to configure the pipeline to do so.

we will add later, all components required pipeline

2024-11-19 21:29 UTC, tpowell-progress commented
@sanghinitin following up

2024-12-03 08:47 UTC, sanghinitin commented
> @sanghinitin following up

https://github.com/chef/ohai/pull/1842

2024-12-06 10:27 UTC, merged